services:
  postgres:
    image: postgres:16
    container_name: users-postgres
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_pass
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
volumes:
  users_data:
